### ISSUE TITLE
Thunderstorm Payload Test 

### ISSUE THREAD

**Issue by NSampson** [M2I-HABET/HABET_Thunderstorm#7]
The new code including the external temperature sensor for the thunderstorm module needs to be tested on the prototype module.  120c3aa729439c06bdcd1d9bbfa3ab8b969ec864

**Comment by matgyver** [comment]
Error in line 23, misspelling caused the code to not run.  Fixed in d46d08499f9487b2de69697cff20fed56a5dc003 

Below is the output from the current code

No GPS
DATA,BME,24.1517,123799,43.8321,979.182,7.04959,ResistanceTemp,Resistance Temp,-242.020,eol
b'0.02,19.17,240420,,,D*4D\r\n'

Please let me know on further testing - @NSampson

**Comment by AustinTrask** [comment]
I fixed the temp resistance probe output.

New output:

b'0.28,72.47,070520,,,A*40\r\n'
No GPS
DATA,BME,19.155,127570,48.6048,992.165,-104.19ResistTemp,17.052,eol

**Comment by matgyver** [comment]
This issue appears to be resolved.  Closing it.  Changes have been merged into the master branch.
